global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'odoo'
    static_configs:
      - targets: ['odoo_alfa:8069']  
    metrics_path: '/metrics'
    scrape_interval: 15s
