version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"                # painel web em :8080
      - "--providers.docker=true"            # monitora containers docker
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"      # HTTP
      - "--entrypoints.websecure.address=:443" # HTTPS
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
